version: '3.8'
services:
  runpod:
    container_name: runpod
    build: .
    volumes:
      - ./libs:/home/widium/libs
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
